import Link from "next/link";
import type { Prisma } from "@/generated/prisma/client";
import { Archive, ArrowLeft, Bot, CircleDot, FolderKanban, LockKeyhole, Plus, Search, UserRound, Workflow } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { getDevCompany } from "@/server/dev-company";
import { createManualProject, createManualTask, updateProjectStatus } from "./actions";
import { KanbanBoard } from "./kanban-board";

export const metadata = { title: "Gestão de projetos" };
export const dynamic = "force-dynamic";
type Params = { project?: string; status?: string; q?: string; error?: string; created?: string };
const projectLabels = { DRAFT: "Aguardando aprovação", ACTIVE: "Ativo", PAUSED: "Arquivado", COMPLETED: "Concluído", CANCELLED: "Cancelado" } as const;
function record(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function sourceLabel(value: unknown) { return String(record(value).source ?? "") === "MANUAL" ? "Criado manualmente" : "Criado com o COO"; }

export default async function TasksPage({ searchParams }: { searchParams: Promise<Params> }) {
  const company = await getDevCompany(), params = await searchParams;
  const selected = params.project ? await prisma.actionPlan.findFirst({ where: { id: params.project, companyId: company.id, status: { not: "CANCELLED" } }, include: { tasks: { where: { status: { not: "CANCELLED" } }, orderBy: { sortOrder: "asc" } } } }) : null;
  if (selected) return <ProjectBoard project={selected} error={params.error} created={params.created} />;

  const statuses = params.status === "archived" ? ["PAUSED", "COMPLETED"] : params.status === "all" ? ["DRAFT", "ACTIVE", "PAUSED", "COMPLETED"] : ["DRAFT", "ACTIVE"];
  const query = params.q?.trim() ?? "";
  const projects = await prisma.actionPlan.findMany({ where: { companyId: company.id, status: { in: statuses as never }, ...(query ? { OR: [{ title: { contains: query, mode: "insensitive" } }, { objective: { contains: query, mode: "insensitive" } }] } : {}) }, orderBy: [{ status: "asc" }, { updatedAt: "desc" }], include: { tasks: { where: { status: { not: "CANCELLED" } }, orderBy: { sortOrder: "asc" } } } });
  const all = await prisma.actionPlan.findMany({ where: { companyId: company.id, status: { notIn: ["CANCELLED"] } }, select: { status: true, tasks: { where: { status: { not: "CANCELLED" } }, select: { status: true } } } });
  const activeCount = all.filter(item => ["ACTIVE", "DRAFT"].includes(item.status)).length, archivedCount = all.filter(item => ["PAUSED", "COMPLETED"].includes(item.status)).length;
  const inProgress = all.flatMap(item => item.tasks).filter(task => task.status === "IN_PROGRESS").length, blocked = all.flatMap(item => item.tasks).filter(task => task.status === "BLOCKED").length;

  return <div className="space-y-6">
    <header className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold text-muted"><FolderKanban className="size-4"/>Execução da fábrica</div><h1 className="mt-2 text-2xl font-semibold tracking-tight">Gestão de projetos</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Planos, tarefas, arquivos e conversas em um só lugar. Você decide quantas frentes quer executar ao mesmo tempo.</p></div><NewProject /></header>
    {params.error ? <p role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{params.error}</p> : null}
    <section className="grid gap-px overflow-hidden rounded-xl border bg-border sm:grid-cols-4">{[{label:"Projetos ativos",value:activeCount,icon:FolderKanban},{label:"Arquivados",value:archivedCount,icon:Archive},{label:"Tarefas em andamento",value:inProgress,icon:Workflow},{label:"Bloqueios",value:blocked,icon:LockKeyhole}].map(({label,value,icon:Icon})=><div key={label} className="bg-white p-4"><Icon className="size-4 text-muted"/><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted">{label}</p></div>)}</section>
    <section><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-1 rounded-xl bg-surface-muted p-1">{[{key:"active",label:"Ativos",count:activeCount},{key:"archived",label:"Arquivados",count:archivedCount},{key:"all",label:"Todos",count:all.length}].map(tab=><Link key={tab.key} href={tab.key === "active" ? "/tarefas" : `/tarefas?status=${tab.key}`} className={`rounded-lg px-3 py-2 text-xs font-semibold ${((params.status ?? "active") === tab.key) ? "bg-white shadow-sm" : "text-muted"}`}>{tab.label} <span className="ml-1 text-[10px]">{tab.count}</span></Link>)}</div><form className="relative"><input type="hidden" name="status" value={params.status ?? "active"}/><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted"/><input name="q" defaultValue={query} placeholder="Buscar projetos" className="h-10 w-full rounded-xl border bg-white pl-9 pr-3 text-sm sm:w-64"/></form></div>
      {projects.length ? <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map(project=>{const done=project.tasks.filter(task=>task.status==="DONE").length, progress=project.tasks.length?Math.round(done/project.tasks.length*100):0, ai=sourceLabel(project.baseline).includes("COO");return <Link key={project.id} href={`/tarefas?project=${project.id}`} className="group rounded-xl border bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#bfc7d1] hover:shadow-[0_12px_32px_rgba(11,19,32,0.06)]"><div className="flex items-start justify-between gap-3"><span className="grid size-9 place-items-center rounded-lg bg-surface-muted"><FolderKanban className="size-4"/></span><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${project.status==="ACTIVE"?"bg-[#e8f1eb] text-[#285f3c]":"bg-surface-muted text-muted"}`}>{projectLabels[project.status]}</span></div><h2 className="mt-4 text-sm font-semibold leading-6 group-hover:text-[#0b3156]">{project.title}</h2><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted">{project.objective}</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-surface-muted"><div className="h-full rounded-full bg-[#0b3156]" style={{width:`${progress}%`}}/></div><div className="mt-3 flex items-center justify-between text-[11px] text-muted"><span>{done}/{project.tasks.length} tarefas</span><span>{progress}%</span></div><div className="mt-4 flex items-center justify-between border-t pt-3 text-[10px] text-muted"><span className="inline-flex items-center gap-1">{ai?<Bot className="size-3"/>:<UserRound className="size-3"/>}{sourceLabel(project.baseline)}</span><span>{project.dueAt?`até ${project.dueAt.toLocaleDateString("pt-BR")}`:"sem prazo"}</span></div></Link>})}</div> : <div className="mt-5 rounded-xl border border-dashed bg-white p-10 text-center"><FolderKanban className="mx-auto size-6 text-muted"/><h2 className="mt-3 font-semibold">Nenhum projeto nesta visão</h2><p className="mt-1 text-sm text-muted">Crie um projeto manual ou aprove um plano preparado pelo COO.</p></div>}
    </section>
  </div>;
}

function NewProject(){return <details className="group relative"><summary className="inline-flex min-h-11 cursor-pointer list-none items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-white"><Plus className="size-4"/>Novo projeto</summary><div className="absolute right-0 z-20 mt-2 w-[min(92vw,420px)] rounded-2xl border bg-white p-5 shadow-xl"><h2 className="font-semibold">Criar projeto manual</h2><p className="mt-1 text-xs leading-5 text-muted">Use para uma iniciativa que não veio de um diagnóstico.</p><form action={createManualProject} className="mt-4 space-y-3"><label className="block text-xs font-semibold">Nome<input name="title" required maxLength={120} placeholder="Ex.: Organizar instalação dos pedidos" className="mt-1.5 w-full rounded-lg border px-3 py-2.5 text-sm"/></label><label className="block text-xs font-semibold">Objetivo<textarea name="objective" required maxLength={600} rows={3} placeholder="O que precisa mudar ao final?" className="mt-1.5 w-full resize-none rounded-lg border px-3 py-2.5 text-sm"/></label><label className="block text-xs font-semibold">Prazo do projeto<select name="windowDays" defaultValue="30" className="mt-1.5 w-full rounded-lg border px-3 py-2.5 text-sm"><option value="7">7 dias</option><option value="14">14 dias</option><option value="30">30 dias</option><option value="60">60 dias</option><option value="90">90 dias</option></select></label><button className="w-full rounded-lg bg-primary px-4 py-3 text-sm font-semibold text-white">Criar projeto</button></form></div></details>}

type ProjectData = Prisma.ActionPlanGetPayload<{ include: { tasks: true } }>;
function ProjectBoard({ project, error, created }: { project: ProjectData; error?: string; created?: string }) {
  const tasks=project.tasks.filter(task=>task.status!=="CANCELLED"),isActive=project.status==="ACTIVE";
  return <div className="space-y-5"><header className="border-b pb-5"><Link href="/tarefas" className="inline-flex items-center gap-2 text-xs font-medium text-muted"><ArrowLeft className="size-3.5"/>Todos os projetos</Link><div className="mt-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-surface-muted px-2 py-1 text-[10px] font-semibold">{projectLabels[project.status]}</span><span className="text-[10px] text-muted">{sourceLabel(project.baseline)}</span></div><h1 className="mt-3 text-2xl font-semibold tracking-tight">{project.title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">{project.objective}</p></div><div className="flex flex-wrap gap-2">{isActive?<NewTask projectId={project.id}/>:null}<form action={updateProjectStatus}><input type="hidden" name="projectId" value={project.id}/><input type="hidden" name="status" value={isActive?"PAUSED":"ACTIVE"}/><button className="min-h-10 rounded-lg border bg-white px-4 text-xs font-semibold">{isActive?"Arquivar projeto":"Reabrir projeto"}</button></form></div></div></header>{error?<p role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{error}</p>:null}{created?<p role="status" className="rounded-xl border border-[#d7e4da] bg-[#f2f7f3] p-4 text-sm text-[#285f3c]">{created==="project"?"Projeto criado. Agora adicione a primeira tarefa.":"Tarefa adicionada ao projeto."}</p>:null}
    <KanbanBoard projectId={project.id} active={isActive} projectDueAt={project.dueAt?.toISOString() ?? null} initialTasks={tasks.map(task=>({id:task.id,title:task.title,description:task.description,priority:task.priority,status:task.status,dueAt:task.dueAt?.toISOString()??null}))}/><div className="flex flex-wrap items-center justify-between gap-3 border-t pt-4 text-xs text-muted"><span className="inline-flex items-center gap-2"><CircleDot className="size-3.5"/>Mudanças de status aparecem no acompanhamento.</span><Link href="/assistente" className="inline-flex items-center gap-2 font-semibold text-foreground"><Bot className="size-4"/>Conversar com o COO</Link></div>
  </div>;
}

function NewTask({projectId}:{projectId:string}){return <details className="group relative"><summary className="inline-flex min-h-10 cursor-pointer list-none items-center gap-2 rounded-lg bg-primary px-4 text-xs font-semibold text-white"><Plus className="size-4"/>Nova tarefa</summary><div className="absolute right-0 z-20 mt-2 w-[min(92vw,440px)] rounded-2xl border bg-white p-5 text-foreground shadow-xl"><h2 className="font-semibold">Adicionar tarefa</h2><p className="mt-1 text-xs text-muted">Ela entra em “A fazer” e pode ser iniciada junto das demais.</p><form action={createManualTask} className="mt-4 space-y-3"><input type="hidden" name="planId" value={projectId}/><label className="block text-xs font-semibold">Título<input name="title" required maxLength={180} className="mt-1.5 w-full rounded-lg border px-3 py-2.5 text-sm" placeholder="O que precisa ser feito?"/></label><label className="block text-xs font-semibold">Como fazer<textarea name="description" maxLength={3000} rows={3} className="mt-1.5 w-full resize-none rounded-lg border px-3 py-2.5 text-sm" placeholder="Contexto para quem executar"/></label><label className="block text-xs font-semibold">Entrega esperada<input name="expectedOutput" maxLength={1000} className="mt-1.5 w-full rounded-lg border px-3 py-2.5 text-sm" placeholder="Como saberemos que terminou?"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-semibold">Prioridade<select name="priority" defaultValue="MEDIUM" className="mt-1.5 w-full rounded-lg border px-3 py-2.5 text-sm"><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option><option value="URGENT">Urgente</option></select></label><label className="block text-xs font-semibold">Prazo<input name="dueDate" type="date" className="mt-1.5 w-full rounded-lg border px-3 py-2.5 text-sm"/></label></div><button className="w-full rounded-lg bg-primary px-4 py-3 text-sm font-semibold text-white">Adicionar tarefa</button></form></div></details>}
