import Link from "next/link";
import { ArrowRight, CheckCircle2, ClipboardList, FileCheck2, Target } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { ReadingDetails } from "@/components/reading-layout";
import { SectionCard } from "@/components/ui";
import { prisma } from "@/lib/prisma";
import { getDevCompany } from "@/server/dev-company";
import { cooPlanSchema } from "@/core/coo-workshop";
import { taskProgress } from "@/core/task-progress";
export const metadata = { title: "Acompanhamento" };
export const dynamic = "force-dynamic";
export default async function FollowUpPage() {
  const company = await getDevCompany();
  const plan = await prisma.actionPlan.findFirst({ where: { companyId: company.id, status: "ACTIVE" }, orderBy: { createdAt: "desc" }, include: { tasks: { orderBy: { sortOrder: "asc" }, include: { evidence: { orderBy: { createdAt: "desc" } } } }, checkins: { where: { status: { not: "OPEN" } }, orderBy: { createdAt: "desc" } } } });
  if (!plan) return <div className="space-y-6"><PageHeader title="Seu progresso começa aqui" description="Aprove um plano para acompanhar a execução e os resultados."/><Link className="inline-flex rounded-lg bg-primary px-5 py-3 text-sm text-white" href="/plano-de-acao">Ver planos de ação</Link></div>;
  const artifacts = await prisma.workspaceArtifact.findMany({ where: { companyId: company.id, taskId: { in: plan.tasks.map(t => t.id) } }, select: { id: true, title: true, taskId: true, confirmedAt: true, interpretation: true } });
  const progress = taskProgress(plan.tasks, artifacts);
  const parsed = cooPlanSchema.safeParse(plan.targetOutcome), primary = parsed.data?.initiatives.find(i => i.kind === "PRIMARY"), action = primary?.actions[0];
  const threadId = typeof Object(plan.baseline).threadId === "string" ? Object(plan.baseline).threadId as string : null;
  const chat = threadId ? "/assistente?chat="+threadId : "/assistente";
  return <div className="mx-auto max-w-6xl space-y-6">
    <PageHeader eyebrow="Evolução da fábrica" title="Veja o que já avançou" description="Atualizado pelos registros das tarefas. Você não precisa responder tudo de novo."/>
    <SectionCard className="p-5 sm:p-7"><div className="flex items-center gap-2 text-xs font-semibold text-primary"><Target className="size-4"/>Prioridade atual</div><h2 className="mt-3 text-xl font-semibold">{primary?.title ?? plan.objective}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-muted">{primary?.facts ?? plan.objective}</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-surface-muted/60 p-4"><h3 className="text-xs font-semibold">O que queremos melhorar</h3><p className="mt-2 text-sm leading-6">{action?.target ?? "Meta ainda não registrada"}</p></div><div className="rounded-xl bg-surface-muted/60 p-4"><h3 className="text-xs font-semibold">Próximo passo</h3><p className="mt-2 text-sm leading-6">{progress.nextTask?.title ?? "Revisar os resultados com o COO e decidir o próximo ciclo."}</p><Link href={progress.nextTask ? "/tarefas/"+progress.nextTask.id : chat} className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-primary">{progress.nextTask ? "Abrir tarefa" : "Conversar com o COO"}<ArrowRight className="size-4"/></Link></div></div><ReadingDetails title="Por que esta prioridade e como acompanhar" className="mt-4"><dl className="grid gap-4 text-sm sm:grid-cols-2">{[["Objetivo",parsed.data?.objective ?? plan.objective],["Hipótese a verificar",primary?.hypothesis],["Indicador",action?.indicator],["Ponto de partida",action?.baseline],["Responsável sugerido",action?.who],["Revisão combinada",action?.reviewCadence]].map(([title,value])=><div key={title}><dt className="text-xs font-semibold text-muted">{title}</dt><dd className="mt-1 leading-6">{value ?? "Ainda não informado"}</dd></div>)}</dl><Link className="mt-4 inline-block text-sm underline" href={"/plano-de-acao?id="+plan.id}>Ver o plano e o 5W2H</Link></ReadingDetails></SectionCard>
    <div className="grid gap-4 sm:grid-cols-3">{[{icon:CheckCircle2,value:progress.completed+" de "+progress.total,label:"Tarefas concluídas"},{icon:ClipboardList,value:progress.recordCount + progress.notes.length,label:"Registros de execução e contexto"},{icon:FileCheck2,value:progress.confirmed.length,label:"Leituras de arquivos confirmadas"}].map(({icon:Icon,value,label})=><SectionCard key={label} className="p-5"><Icon className="size-5 text-primary"/><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted">{label}</p></SectionCard>)}</div>
    <SectionCard className="p-5"><div className="flex justify-between gap-3 text-sm"><h2 className="font-semibold">Execução do plano</h2><span>{progress.percent}%</span></div><div role="progressbar" aria-label="Tarefas concluídas" aria-valuenow={progress.percent} aria-valuemin={0} aria-valuemax={100} className="mt-3 h-2 overflow-hidden rounded-full bg-surface-muted"><div className="h-full rounded-full bg-primary" style={{width:progress.percent+"%"}}/></div><p className="mt-3 text-xs leading-5 text-muted">Esta barra mede tarefas concluídas, não aumento de produtividade ou lucro.</p><ol className="mt-4 divide-y">{plan.tasks.filter(t=>t.status!=="CANCELLED").map(t=><li key={t.id}><Link href={"/tarefas/"+t.id} className="flex items-start gap-3 py-3 text-sm"><span className={"mt-1 size-3 shrink-0 rounded-full "+(t.status==="DONE"?"bg-primary":"border-2 border-slate-300")}/><span className="min-w-0 flex-1">{t.title}</span><span className="shrink-0 text-xs text-muted">{t.status==="DONE"?"Concluída":t.status==="IN_PROGRESS"?"Em andamento":"Pendente"}</span></Link></li>)}</ol></SectionCard>
    <div className="grid gap-5 md:grid-cols-2"><SectionCard className="p-5"><h2 className="text-base font-semibold">O que foi aplicado</h2>{progress.applied.length?progress.applied.map((n,i)=><p key={i} className="mt-3 text-sm leading-6">{n.text}<Link className="ml-2 text-xs underline" href={"/tarefas/"+n.taskId}>Ver origem</Link></p>):<p className="mt-3 text-sm text-muted">{progress.recordCount?progress.recordCount+" registros de execução salvos. Os detalhes estão nas tarefas.":"Ainda sem registro de execução. Comece pela tarefa indicada acima."}</p>}</SectionCard><SectionCard className="p-5"><h2 className="text-base font-semibold">Resultados observados</h2><p className="mt-1 text-xs text-muted">Relatos e leituras confirmadas — não uma conclusão automática de melhoria.</p>{!progress.results.length&&!progress.confirmed.length?<p className="mt-3 text-sm text-muted">Ainda sem resultados registrados. Preencha uma tarefa ou envie a medição para comparar com o ponto de partida.</p>:<div className="mt-3 space-y-3">{progress.results.map((n,i)=><p key={i} className="text-sm leading-6">{n.text}<Link href={"/tarefas/"+n.taskId} className="ml-2 text-xs underline">Ver origem</Link></p>)}{progress.confirmed.map(a=><ReadingDetails key={a.id} title={a.title}><p className="text-sm leading-6">{a.summary}</p><dl className="mt-3 space-y-3">{a.observations.map((o,i)=><div key={i}><dt className="text-xs font-semibold">{o.label}</dt><dd className="text-sm">{o.value}<span className="block text-xs text-muted">Origem: {o.source}</span></dd></div>)}</dl>{a.uncertainties.length?<p className="mt-3 text-xs text-amber-800">Ainda incerto: {a.uncertainties.join("; ")}</p>:null}<Link className="mt-3 inline-block text-xs underline" href={"/tarefas/"+a.taskId}>Abrir arquivo na tarefa</Link></ReadingDetails>)}</div>}</SectionCard></div>
    <ReadingDetails title={"Dificuldades registradas · "+progress.blockers.length}><p className="text-xs text-muted">Histórico do que foi relatado; confirme com o COO se ainda está bloqueando a execução.</p>{progress.blockers.map((n,i)=><p key={i} className="mt-3 text-sm leading-6">{n.text}<Link href={"/tarefas/"+n.taskId} className="ml-2 text-xs underline">Abrir tarefa</Link></p>)}{!progress.blockers.length?<p className="mt-3 text-sm">Nenhuma dificuldade registrada — isso não significa que não exista.</p>:null}</ReadingDetails>
    {plan.checkins.length?<ReadingDetails title="Avaliações anteriores"><div className="space-y-4">{plan.checkins.map(c=><div key={c.id}><p className="text-xs text-muted">{c.createdAt.toLocaleDateString("pt-BR")}</p><p className="mt-2 whitespace-pre-line text-sm leading-6">{c.aiEvaluation ?? c.summary}</p></div>)}</div></ReadingDetails>:null}
  </div>;
}
