"use client";
import { useRef,useState } from "react";
import { productionState,validateProductionEvent,validateFormValues,type ExecutionGuide,type ProductionEvent } from "@/core/task-execution";
import { eventsFrom,type SavedRecord } from "@/core/task-records";
const labels={START:"Iniciar lote",PAUSE:"Parou",RESUME:"Retomou",OUTPUT:"Saíram peças",FINISH:"Encerrar lote"};
export function TaskRecorder({taskId,guide,initialRecords,canRecord}:{taskId:string;guide:ExecutionGuide;initialRecords:SavedRecord[];canRecord:boolean}){
 const [records,setRecords]=useState(initialRecords),[demoRecords,setDemoRecords]=useState<SavedRecord[]>([]),[demo,setDemo]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const lock=useRef(false),requestRef=useRef<{payload:string;id:string}|null>(null);
 const [order,setOrder]=useState(""),[product,setProduct]=useState(""),[note,setNote]=useState(""),[quantity,setQuantity]=useState("1"),[values,setValues]=useState<Record<string,string>>({});
 const recording=guide.recording;if(!recording)return null;
 const displayed=demo?demoRecords:records,live=displayed.filter(r=>!r.voided),state=productionState(eventsFrom(displayed)),enabled=demo||canRecord;
 async function save(intent:"SAVE"|"UNDO",event?:ProductionEvent["event"]){
  if(lock.current||!enabled)return;lock.current=true;setBusy(true);setError("");setNotice("");
  try{
   const data=event?validateProductionEvent(eventsFrom(displayed),{event,order,product,note,quantity:Number(quantity)}):undefined;
   const form=intent==="SAVE"&&!event?validateFormValues(guide,values):undefined;
   if(demo){
    if(intent==="UNDO")setDemoRecords(previous=>previous.slice(0,-1));
    else setDemoRecords(previous=>[...previous,{id:crypto.randomUUID(),at:new Date().toISOString(),kind:data?"PRODUCTION_EVENT":"FORM_ENTRY",...(data?{event:data}:{values:form})}]);
    setNotice("Teste feito. Nenhuma informação de produção foi salva.");
   }else{
    const body={intent,...(data?{event:data}:{}),...(form?{values:form}:{})},payload=JSON.stringify(body);
    if(requestRef.current?.payload!==payload)requestRef.current={payload,id:crypto.randomUUID()};
    const response=await fetch(`/api/tasks/${encodeURIComponent(taskId)}/records`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,requestId:requestRef.current!.id})});
    const result=await response.json();if(!response.ok)throw Error(result.error??"Não foi possível salvar.");
    setRecords(result.records);requestRef.current=null;setNotice(intent==="UNDO"?"Último registro desfeito. O histórico da correção foi preservado.":"Registro salvo no banco local.");
   }
   if(event==="PAUSE")setNote("");if(form)setValues({});
  }catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.");}finally{lock.current=false;setBusy(false);}
 }
 const fieldClass="mt-1 w-full min-w-0 rounded-lg border bg-white px-3 py-2 text-sm";
 return <section className="space-y-4 rounded-2xl border bg-white p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{recording.title}</h2><p className="mt-1 text-sm text-muted">{recording.instructions}</p></div><button disabled={busy} className="rounded-lg border px-3 py-2 text-sm font-bold" onClick={()=>{setDemo(!demo);setError("");setNotice("");}}>{demo?"Sair do teste":"Testar sem salvar"}</button></div>
 {demo?<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Modo de teste: dados fictícios, descartados ao sair da página. Não contam como execução ou resultado.</p>:!canRecord?<p className="rounded-lg bg-surface-muted p-3 text-sm">Prévia do formulário. Os registros reais serão liberados após aprovar o plano e liberar esta tarefa. Você já pode testar sem salvar.</p>:<p className="text-xs text-muted">Os registros reais ficam ligados a esta tarefa e disponíveis para o acompanhamento do COO.</p>}
 {recording.kind==="PRODUCTION_LOG"?<div className="space-y-4"><p className="text-sm font-bold">{state.mode==="IDLE"?"Nenhum lote aberto":`${state.mode==="PAUSED"?"Em parada":"Em produção"} · ${state.order} · ${state.product}`}</p><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Pedido ou lote<input className={fieldClass} value={order} disabled={!enabled||busy||state.mode!=="IDLE"} onChange={e=>setOrder(e.target.value)} placeholder="Ex.: pedido 104 — lote A"/></label><label className="text-sm">Tipo de peça<input className={fieldClass} value={product} disabled={!enabled||busy||state.mode!=="IDLE"} onChange={e=>setProduct(e.target.value)} placeholder="Ex.: porta MDF 18 mm"/></label><label className="text-sm">Peças boas que saíram agora<input type="number" min="1" step="1" className={fieldClass} value={quantity} disabled={!enabled||busy} onChange={e=>setQuantity(e.target.value)}/></label><label className="text-sm">Motivo, se parou<input className={fieldClass} value={note} disabled={!enabled||busy} onChange={e=>setNote(e.target.value)} placeholder="Ex.: aguardando projeto"/></label></div><div className="flex flex-wrap gap-2">{(Object.keys(labels) as Array<keyof typeof labels>).map(event=><button key={event} disabled={!enabled||busy||(event==="START"?state.mode!=="IDLE":event==="RESUME"?state.mode!=="PAUSED":state.mode!=="RUNNING")} className="rounded-lg bg-primary px-4 py-3 text-sm font-bold text-white disabled:opacity-35" onClick={()=>save("SAVE",event)}>{labels[event]}</button>)}</div><p className="text-xs leading-5 text-muted">Horário automático. Registre a quantidade do lote que saiu, não precisa clicar a cada peça. Um posto e um lote por vez. Tempo decorrido não é horas-pessoa.</p><p className="text-sm">Até o último registro: {state.workMinutes} min em produção · {state.pauseMinutes} min de parada.</p><p className="text-xs text-muted">Não compare quantidades de peças diferentes como produtividade. Registre retrabalho e contexto no acompanhamento.</p></div>:<form className="space-y-4" onSubmit={e=>{e.preventDefault();void save("SAVE");}}><div className="grid gap-4 sm:grid-cols-2">{recording.fields.map(field=><label key={field.key} className="min-w-0 text-sm font-semibold">{field.label}{field.required?" *":""}<input className={fieldClass} type={field.type==="NUMBER"?"number":"text"} min={field.type==="NUMBER"?0:undefined} step={field.type==="NUMBER"?"any":undefined} required={field.required} disabled={!enabled||busy} value={values[field.key]??""} placeholder={`Ex.: ${field.example}`} onChange={e=>setValues({...values,[field.key]:e.target.value})}/><span className="mt-1 block text-xs font-normal text-muted">{field.hint}</span></label>)}</div><button disabled={!enabled||busy} className="rounded-lg bg-primary px-4 py-3 text-sm font-bold text-white disabled:opacity-35">{busy?"Salvando…":"Salvar anotação"}</button><p className="text-xs text-muted">Os exemplos nos campos são fictícios. Preencha somente o que observou.</p></form>}
 {error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}<p role="status" className="text-sm text-primary">{notice}</p>
 <div className="space-y-2"><h3 className="text-sm font-bold">{demo?"Registros de teste":"Anotações salvas"} ({live.length})</h3>{!live.length?<p className="text-sm text-muted">Nenhuma anotação ainda.</p>:live.slice(-30).map(r=><article key={r.id} className="rounded-lg border p-3 text-sm"><p className="font-bold">{new Date(r.at).toLocaleString("pt-BR")}{r.event?` · ${labels[r.event.event]}`:""}</p>{r.event?<p className="mt-1 break-words">{r.event.order} · {r.event.product}{r.event.event==="OUTPUT"?` · ${r.event.quantity} peças boas`:""}{r.event.event==="PAUSE"?` · ${r.event.note}`:""}</p>:<dl className="mt-2 grid gap-2 sm:grid-cols-2">{recording.fields.map(f=><div key={f.key}><dt className="text-xs text-muted">{f.label}</dt><dd className="break-words">{r.values?.[f.key]||"Não informado"}</dd></div>)}</dl>}</article>)}{live.length>30?<p className="text-xs text-muted">Mostrando as últimas 30 anotações; todas permanecem salvas.</p>:null}<button disabled={!enabled||busy||!live.length} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-35" onClick={()=>save("UNDO")}>Desfazer última anotação</button></div>
 </section>;
}
