import type { DiagnosticMethodDefinition } from "@/core/diagnostic-method";

export const PROVISIONAL_DIAGNOSTIC_METHOD: DiagnosticMethodDefinition = {
  code: "MOVEIS-OPERACIONAL-V1",
  name: "Diagnóstico Operacional de Fábricas de Móveis",
  version: 1,
  objective:
    "Identificar o principal gargalo operacional que reduz produtividade, eficiência, prazo ou lucro em uma fábrica de móveis.",
  appliesTo: ["Fábricas de móveis sob medida", "Fábricas de móveis seriados"],
  doesNotApplyTo: [],
  cycleDays: 7,
  maxActiveTasks: 3,
  adaptiveQuestions: [],
  questions: [
    {
      code: "FLUXO-001",
      pillar: "Fluxo e prazo",
      prompt: "Com que frequência os pedidos são entregues depois do prazo prometido?",
      helpText: "Considere os últimos 30 dias.",
      answerType: "SCALE",
      options: ["Nunca", "Raramente", "às vezes", "Frequentemente", "Quase sempre"],
      required: true,
      weight: 1,
      scoringRule: "1 = quase nunca; 5 = quase sempre",
    },
    {
      code: "FLUXO-002",
      pillar: "Fluxo e prazo",
      prompt: "Quanto tempo os pedidos ficam parados aguardando a próxima etapa?",
      helpText: "Pense no tempo de espera entre projeto, corte, montagem e acabamento.",
      answerType: "SCALE",
      options: [
        "Quase não esperam",
        "Esperam pouco",
        "Esperam um tempo moderado",
        "Esperam muito",
        "Esperam mais do que produzem",
      ],
      required: true,
      weight: 1,
      scoringRule: "1 = quase não esperam; 5 = passam mais tempo esperando do que produzindo",
    },
    {
      code: "FLUXO-003",
      pillar: "Fluxo e prazo",
      prompt: "Existe acúmulo recorrente de pedidos ou peças antes de alguma etapa?",
      helpText: "Exemplos: fila antes do corte, CNC, montagem ou pintura.",
      answerType: "SCALE",
      options: ["Não existe", "Acontece raramente", "Acontece às vezes", "Acontece com frequência", "A fila é constante"],
      required: true,
      weight: 1,
      scoringRule: "1 = não existe fila relevante; 5 = fila constante e crescente",
    },
    {
      code: "CAPACIDADE-001",
      pillar: "Capacidade e gargalo",
      prompt: "Existe uma máquina, setor ou pessoa que frequentemente limita o ritmo da fábrica?",
      helpText: "Considere onde o restante da operação precisa esperar.",
      answerType: "SCALE",
      options: ["Não limita", "Limita raramente", "Limita às vezes", "Limita com frequência", "É uma limitação constante"],
      required: true,
      weight: 1,
      scoringRule: "1 = capacidade equilibrada; 5 = restrição evidente e recorrente",
    },
    {
      code: "CAPACIDADE-002",
      pillar: "Capacidade e gargalo",
      prompt: "Com que frequência paradas, setups ou manutenção reduzem a capacidade planejada?",
      helpText: "Inclua paradas de máquina e trocas demoradas.",
      answerType: "SCALE",
      options: ["Nunca", "Raramente", "às vezes", "Frequentemente", "Quase todos os dias"],
      required: true,
      weight: 1,
      scoringRule: "1 = impacto mínimo; 5 = impacto diário e relevante",
    },
    {
      code: "CAPACIDADE-003",
      pillar: "Capacidade e gargalo",
      prompt: "A fábrica mede horas disponíveis, horas carregadas e capacidade real por etapa?",
      helpText: "A falta de medição aumenta a incerteza do diagnóstico.",
      answerType: "SCALE",
      options: ["Medimos e usamos os dados", "Medimos quase tudo", "Medimos só uma parte", "Raramente medimos", "Não medimos"],
      required: true,
      weight: 1,
      scoringRule: "1 = mede e usa os dados; 5 = decide sem conhecer a capacidade",
    },
    {
      code: "QUALIDADE-001",
      pillar: "Qualidade e retrabalho",
      prompt: "Com que frequência peças ou pedidos precisam voltar para correção?",
      helpText: "Considere erros de projeto, medida, corte, usinagem, montagem e acabamento.",
      answerType: "SCALE",
      options: ["Nunca", "Raramente", "às vezes", "Frequentemente", "Quase sempre"],
      required: true,
      weight: 1,
      scoringRule: "1 = quase nunca; 5 = retrabalho recorrente e relevante",
    },
    {
      code: "QUALIDADE-002",
      pillar: "Qualidade e retrabalho",
      prompt: "Os erros são identificados cedo, antes de avançarem para outras etapas?",
      helpText: "Erros descobertos apenas na montagem ou instalação indicam custo maior.",
      answerType: "SCALE",
      options: ["Quase sempre no início", "Geralmente no início", "às vezes cedo, às vezes tarde", "Geralmente no final", "Quase sempre no final"],
      required: true,
      weight: 1,
      scoringRule: "1 = erros detectados cedo; 5 = erros descobertos no final",
    },
    {
      code: "QUALIDADE-003",
      pillar: "Qualidade e retrabalho",
      prompt: "A fábrica registra as causas dos erros ou apenas corrige o problema quando aparece?",
      helpText: "Registrar causa é diferente de apenas registrar que houve retrabalho.",
      answerType: "SCALE",
      options: ["Registramos e tratamos a causa", "Registramos a maioria", "Registramos algumas", "Raramente registramos", "Só corrigimos quando aparece"],
      required: true,
      weight: 1,
      scoringRule: "1 = causa registrada e tratada; 5 = problema repetido sem registro",
    },
    {
      code: "MATERIAIS-001",
      pillar: "Materiais e informação",
      prompt: "Com que frequência a produção para por falta de material ou componente?",
      helpText: "Inclua MDF, ferragens, tintas, acessórios e itens comprados.",
      answerType: "SCALE",
      options: ["Nunca", "Raramente", "às vezes", "Frequentemente", "Quase todos os dias"],
      required: true,
      weight: 1,
      scoringRule: "1 = não para; 5 = parada frequente por falta de material",
    },
    {
      code: "MATERIAIS-002",
      pillar: "Materiais e informação",
      prompt: "Os pedidos chegam à produção com projeto, medidas e informações completas?",
      helpText: "Considere alterações, dúvidas e informações que precisam ser buscadas depois.",
      answerType: "SCALE",
      options: ["Sempre completas", "Quase sempre completas", "às vezes incompletas", "Frequentemente incompletas", "Quase sempre incompletas"],
      required: true,
      weight: 1,
      scoringRule: "1 = informação completa; 5 = informação frequentemente incompleta",
    },
    {
      code: "MATERIAIS-003",
      pillar: "Materiais e informação",
      prompt: "A empresa compra materiais com urgência ou mantém estoque excessivo por falta de planejamento?",
      helpText: "Considere compras emergenciais e material parado.",
      answerType: "SCALE",
      options: ["Não acontece", "Acontece raramente", "Acontece às vezes", "Acontece com frequência", "É parte da rotina"],
      required: true,
      weight: 1,
      scoringRule: "1 = fluxo previsível; 5 = urgência e excesso acontecem juntos",
    },
    {
      code: "GESTAO-001",
      pillar: "Gestão e padronização",
      prompt: "As etapas principais têm uma forma padrão de trabalho que as pessoas conseguem seguir?",
      helpText: "Pode ser um procedimento simples, visual ou documentado.",
      answerType: "SCALE",
      options: ["Padrão claro e seguido", "Padrão seguido na maioria das vezes", "Depende da pessoa ou do dia", "Pouco padronizado", "Cada pessoa faz de um jeito"],
      required: true,
      weight: 1,
      scoringRule: "1 = padrão claro e seguido; 5 = cada pessoa faz de um jeito",
    },
    {
      code: "GESTAO-002",
      pillar: "Gestão e padronização",
      prompt: "As prioridades da produção mudam durante o dia sem um critério claro?",
      helpText: "Mudanças constantes podem gerar perda de ritmo e retrabalho.",
      answerType: "SCALE",
      options: ["Nunca", "Raramente", "às vezes", "Frequentemente", "O tempo todo"],
      required: true,
      weight: 1,
      scoringRule: "1 = sequência estável; 5 = urgências mudam o plano o tempo todo",
    },
    {
      code: "GESTAO-003",
      pillar: "Gestão e padronização",
      prompt: "Os problemas têm um responsável, prazo e indicador de acompanhamento?",
      helpText: "Sem dono e prazo, o problema tende a voltar.",
      answerType: "SCALE",
      options: ["Sempre", "Na maioria das vezes", "Em alguns problemas", "Raramente", "Nunca"],
      required: true,
      weight: 1,
      scoringRule: "1 = gestão visóvel; 5 = problemas ficam sem dono ou acompanhamento",
    },
  ],
  bottleneckRules: [
    {
      code: "GARGALO-FLUXO",
      name: "Gargalo de fluxo e prazo",
      definition: "Pedidos acumulam ou atrasam porque o fluxo possui espera ou sequência instável.",
      supportingSignals: ["Atrasos", "Tempo parado", "Fila entre etapas"],
      requiredEvidence: ["Exemplos de pedidos atrasados", "Etapa onde ocorre a espera"],
      contradictingEvidence: ["Fluxo estável e entrega dentro do prazo"],
      decisionRule: "Pilar Fluxo e prazo com maior média e evidência de fila ou espera.",
      minimumConfidence: 0.7,
      followUpQuestions: ["Qual etapa concentra a fila?", "Qual é o tempo médio parado?"],
    },
    {
      code: "GARGALO-CAPACIDADE",
      name: "Gargalo de capacidade",
      definition: "Uma etapa, recurso ou máquina limita o ritmo do sistema.",
      supportingSignals: ["Recurso sobrecarregado", "Paradas", "Setups", "Fila antes do recurso"],
      requiredEvidence: ["Recurso limitante", "Exemplo de fila ou parada"],
      contradictingEvidence: ["Capacidade disponível e ausência de fila"],
      decisionRule: "Pilar Capacidade e gargalo com maior média e uma restrição observável.",
      minimumConfidence: 0.7,
      followUpQuestions: ["Qual recurso limita o ritmo?", "Quantas horas são perdidas por semana?"],
    },
    {
      code: "GARGALO-QUALIDADE",
      name: "Gargalo de qualidade e retrabalho",
      definition: "Erros e retrabalho consomem capacidade e atrasam a entrega.",
      supportingSignals: ["Retorno de peças", "Correções", "Erros descobertos no final"],
      requiredEvidence: ["Tipo de retrabalho", "Etapa de origem ou descoberta"],
      contradictingEvidence: ["Baixo retrabalho e aprovação na primeira passagem"],
      decisionRule: "Pilar Qualidade e retrabalho com maior média e ocorrência repetida.",
      minimumConfidence: 0.7,
      followUpQuestions: ["Qual erro mais se repete?", "Quantas horas são gastas corrigindo?"],
    },
    {
      code: "GARGALO-MATERIAIS",
      name: "Gargalo de materiais e informação",
      definition: "A produção perde ritmo por falta de material ou informação completa.",
      supportingSignals: ["Paradas por material", "Compras urgentes", "Projeto incompleto"],
      requiredEvidence: ["Material ou informação faltante", "Pedido afetado"],
      contradictingEvidence: ["Materiais e informações disponíveis no momento correto"],
      decisionRule: "Pilar Materiais e informação com maior média e uma interrupção comprovada.",
      minimumConfidence: 0.7,
      followUpQuestions: ["Qual item ou informação mais bloqueia?", "Quantos pedidos são afetados?"],
    },
    {
      code: "GARGALO-GESTAO",
      name: "Gargalo de gestão e padronização",
      definition: "A falta de padrão, prioridade ou responsabilidade gera variabilidade operacional.",
      supportingSignals: ["Cada pessoa trabalha de um jeito", "Prioridades mudam", "Problemas sem dono"],
      requiredEvidence: ["Exemplo de variação", "Problema sem responsável ou padrão"],
      contradictingEvidence: ["Padrões claros e rotina de acompanhamento consistente"],
      decisionRule: "Pilar Gestão e padronização com maior média e exemplos recorrentes.",
      minimumConfidence: 0.7,
      followUpQuestions: ["Qual processo não possui padrão?", "Quem deveria decidir a prioridade?"],
    },
  ],
  abstentionRules: [
    "Não concluir se todas as respostas estiverem ausentes.",
    "Não concluir se os dois maiores pilares tiverem médias próximas e não houver evidência complementar.",
    "Pedir evidência adicional quando a confiança estimada ficar abaixo de 0.7.",
    "Não inventar método, gargalo, métrica ou resultado que não esteja no contexto.",
  ],
  methods: [
    {
      code: "FLUXO-FIFO-V1",
      name: "Fluxo e fila controlada",
      version: 1,
      description: "Reduzir espera e atrasos controlando a liberação e a sequência dos pedidos.",
      applicabilityRules: ["Gargalo de fluxo e prazo"],
      contraindications: [],
      tradeOffs: ["Pode reduzir a quantidade de pedidos iniciados ao mesmo tempo para melhorar o prazo."],
      indicators: [],
      minimumEvidence: [],
      abandonmentRules: [],
      steps: [
        { order: 1, title: "Mapear espera", description: "Registrar onde cinco pedidos aguardam entre etapas.", suggestedOwner: "Gestor da fábrica", dueInDays: 3, expectedOutput: "Mapa simples de filas", indicator: "Tempo parado por etapa", requiredEvidence: "Registro de cinco pedidos" },
        { order: 2, title: "Definir fila máxima", description: "Estabelecer um limite visual de trabalho antes da etapa crítica.", suggestedOwner: "Responsável pela produção", dueInDays: 5, expectedOutput: "Limite de WIP definido", indicator: "Quantidade de pedidos em fila", requiredEvidence: "Quadro ou planilha atualizada" },
      ],
      successCriteria: ["Redução do tempo parado", "Melhora no cumprimento do prazo"],
    },
    {
      code: "GARGALO-CAPACIDADE-V1",
      name: "Gestão da restrição",
      version: 1,
      description: "Medir, proteger e aumentar o resultado do recurso que limita o sistema.",
      applicabilityRules: ["Gargalo de capacidade"],
      contraindications: [],
      tradeOffs: ["Outras etapas podem operar com menor prioridade para proteger a restrição."],
      indicators: [],
      minimumEvidence: [],
      abandonmentRules: [],
      steps: [
        { order: 1, title: "Confirmar a restrição", description: "Medir fila, disponibilidade e produção do recurso crítico.", suggestedOwner: "Gestor de produção", dueInDays: 5, expectedOutput: "Baseline do gargalo", indicator: "Horas produtivas do recurso", requiredEvidence: "Registro de uma semana" },
        { order: 2, title: "Proteger a capacidade", description: "Remover interrupções evitáveis e priorizar o trabalho que usa a restrição.", suggestedOwner: "Líder da etapa", dueInDays: 7, expectedOutput: "Rotina de proteção", indicator: "Produção por hora do gargalo", requiredEvidence: "Controle diário" },
      ],
      successCriteria: ["Aumento do throughput", "Redução da fila antes do recurso"],
    },
    {
      code: "QUALIDADE-DMAIC-V1",
      name: "Redução de retrabalho",
      version: 1,
      description: "Usar investigação estruturada para reduzir a causa mais frequente de retrabalho.",
      applicabilityRules: ["Gargalo de qualidade e retrabalho"],
      contraindications: [],
      tradeOffs: ["Exige registrar causas antes de escolher a solução."],
      indicators: [],
      minimumEvidence: [],
      abandonmentRules: [],
      steps: [
        { order: 1, title: "Definir o defeito", description: "Escolher um tipo de retrabalho e medir sua frequência.", suggestedOwner: "Gestor da fábrica", dueInDays: 3, expectedOutput: "Problema delimitado", indicator: "Ocorrências do defeito", requiredEvidence: "Amostra de pedidos" },
        { order: 2, title: "Testar causa", description: "Investigar a causa provável e aplicar uma correção piloto.", suggestedOwner: "Responsável pelo processo", dueInDays: 7, expectedOutput: "Ação piloto", indicator: "Taxa de retrabalho", requiredEvidence: "Comparação antes/depois" },
      ],
      successCriteria: ["Redução do retrabalho", "Maior aprovação na primeira passagem"],
    },
    {
      code: "MATERIAIS-PUXADA-V1",
      name: "Disponibilidade de materiais e informação",
      version: 1,
      description: "Garantir que material e informação estejam prontos antes da liberação do pedido.",
      applicabilityRules: ["Gargalo de materiais e informação"],
      contraindications: [],
      tradeOffs: ["Pode reduzir liberações imediatas enquanto os pré-requisitos não estiverem completos."],
      indicators: [],
      minimumEvidence: [],
      abandonmentRules: [],
      steps: [
        { order: 1, title: "Listar bloqueios", description: "Registrar materiais e informações que bloquearam pedidos recentes.", suggestedOwner: "Gestor ou comprador", dueInDays: 3, expectedOutput: "Lista de bloqueios", indicator: "Pedidos bloqueados", requiredEvidence: "Registro de pedidos" },
        { order: 2, title: "Criar checklist de liberação", description: "Definir os itens mínimos para liberar um pedido à produção.", suggestedOwner: "Responsável por projetos", dueInDays: 7, expectedOutput: "Checklist de liberação", indicator: "Paradas por falta de informação", requiredEvidence: "Checklist aplicado" },
      ],
      successCriteria: ["Menos paradas por falta de material", "Menos pedidos liberados incompletos"],
    },
    {
      code: "PADRAO-GESTAO-V1",
      name: "Trabalho padronizado e rotina de gestão",
      version: 1,
      description: "Criar padrões simples, responsáveis claros e acompanhamento frequente.",
      applicabilityRules: ["Gargalo de gestão e padronização"],
      contraindications: [],
      tradeOffs: ["Exige disciplina de registro e revisão antes de gerar ganhos sustentáveis."],
      indicators: [],
      minimumEvidence: [],
      abandonmentRules: [],
      steps: [
        { order: 1, title: "Escolher processo crítico", description: "Selecionar o processo com maior impacto e variação.", suggestedOwner: "Gestor da fábrica", dueInDays: 2, expectedOutput: "Processo priorizado", indicator: "Variação do resultado", requiredEvidence: "Exemplos do processo" },
        { order: 2, title: "Documentar o padrão", description: "Criar uma sequência visual e um critério simples de saída.", suggestedOwner: "Responsável pelo processo", dueInDays: 7, expectedOutput: "Padrão visual", indicator: "Aderência ao padrão", requiredEvidence: "Padrão publicado e usado" },
      ],
      successCriteria: ["Menor variação entre pessoas", "Mais problemas com dono e prazo"],
    },
  ],
};


