import type { DiagnosticMethodDefinition } from "@/core/diagnostic-method";

export const ROTA30_METHOD_CODE = "MOVEIS-OPERACIONAL-ROTA-V1";

export const ROTA30_METHOD_BY_PILLAR: Record<string, string> = {
  "Fluxo e prazo": "ROTA-FLUXO-FILA-CONTROLADA",
  "Capacidade e gargalo": "ROTA-GESTAO-RESTRICAO",
  "Qualidade e retrabalho": "ROTA-REDUCAO-RETRABALHO",
  "Materiais e informação": "ROTA-LIBERACAO-COMPLETA",
  "Gestão e padronização": "ROTA-TRABALHO-PADRONIZADO",
};

export const ROTA30_DIAGNOSTIC_METHOD: DiagnosticMethodDefinition = {
  code: ROTA30_METHOD_CODE,
  name: "Método ROTA 30 para Fábricas de Móveis",
  version: 2,
  objective:
    "Identificar uma oportunidade operacional com evidências e transformá-la em um ciclo acompanhado de melhoria de 30 dias.",
  appliesTo: [
    "Fábricas de móveis sob medida",
    "Fábricas de móveis seriados",
    "Operações mistas de produção discreta",
  ],
  doesNotApplyTo: [
    "Auditoria financeira, contábil ou regulatéria",
    "Projeto completo de ERP, MRP, MES ou PCP",
    "Laudo de segurança, manutenção especializada ou engenharia detalhada",
  ],
  cycleDays: 30,
  maxActiveTasks: 3,
  adaptiveQuestions: [
    {
      code: "ADP-001",
      prompt: "Qual destas duas situações mais prejudica a fábrica hoje?",
      helpText: "Escolha a que exige atenção primeiro.",
      options: null,
    },
    {
      code: "ADP-002",
      prompt: "Qual é a principal consequência desse problema?",
      helpText: "Depois indique se o impacto é baixo, médio ou alto.",
      options: [
        "Atraso",
        "Perda de produção",
        "Retrabalho ou sucata",
        "Custo adicional",
        "Hora extra",
        "Reclamação ou perda de cliente",
        "Desgaste da equipe",
        "Outro",
      ],
    },
    {
      code: "ADP-003",
      prompt: "Qual fato recente sustenta essa percepção?",
      helpText: "Cite um pedido, etapa, ocorrência, quantidade ou tempo.",
      options: null,
    },
  ],
  questions: [
    {
      code: "FLUXO-001",
      pillar: "Fluxo e prazo",
      prompt: "Quantos pedidos foram entregues depois do prazo prometido?",
      helpText: "Considere os pedidos concluídos nos últimos 30 dias.",
      answerType: "SCALE",
      options: ["Nenhum ou quase nenhum", "Alguns pedidos", "Muitos ou a maioria", "Não sei/não acompanhamos"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "FLUXO-002",
      pillar: "Fluxo e prazo",
      prompt: "Os pedidos ficam parados esperando a próxima etapa?",
      helpText: "Pense no tempo entre projeto, corte, usinagem, montagem e acabamento.",
      answerType: "SCALE",
      options: ["Quase não ficam parados", "Param em algumas etapas", "Passam muito tempo parados", "Não sei/não acompanhamos"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "FLUXO-003",
      pillar: "Fluxo e prazo",
      prompt: "Existe fila de peças ou pedidos antes de alguma etapa?",
      helpText: "Exemplo: fila antes do corte, CNC, montagem ou pintura.",
      answerType: "SCALE",
      options: ["Raramente existe fila", "A fila aparece e depois reduz", "A fila é constante ou aumenta", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "FLUXO-004",
      pillar: "Fluxo e prazo",
      prompt: "A fábrica inicia mais pedidos do que consegue terminar?",
      helpText: "Observe se muitos pedidos ficam abertos ao mesmo tempo.",
      answerType: "SCALE",
      options: ["Raramente", "Acontece em alguns períodos", "Acontece quase sempre", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "FLUXO-005",
      pillar: "Fluxo e prazo",
      prompt: "A empresa sabe quanto tempo um pedido leva do início à entrega?",
      helpText: "Considere se existe um número acompanhado, não apenas uma estimativa.",
      answerType: "SCALE",
      options: ["Mede e acompanha", "Tem apenas uma estimativa", "Não mede", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = parcial; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "CAP-001",
      pillar: "Capacidade e gargalo",
      prompt: "Existe uma máquina, setor ou pessoa que limita o ritmo da fábrica?",
      helpText: "Considere onde o restante da operação precisa esperar.",
      answerType: "SCALE",
      options: ["Raramente limita", "Limita em alguns períodos", "Limita quase sempre", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "CAP-002",
      pillar: "Capacidade e gargalo",
      prompt: "Falhas de máquina interrompem a produção?",
      helpText: "Considere quebras e paradas não planejadas nos últimos 30 dias.",
      answerType: "SCALE",
      options: ["Raramente", "Algumas vezes no mês", "Toda semana ou quase todo dia", "Não sei/não registramos"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "CAP-003",
      pillar: "Capacidade e gargalo",
      prompt: "Trocas e preparações de máquina consomem muito tempo?",
      helpText: "Pense em setup, regulagem, ferramenta e limpeza.",
      answerType: "SCALE",
      options: ["Pouco tempo", "Tempo relevante", "Muito tempo ou várias vezes ao dia", "Não sei/não medimos"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "CAP-004",
      pillar: "Capacidade e gargalo",
      prompt: "A equipe precisa fazer hora extra para cumprir os prazos?",
      helpText: "Considere os últimos 30 dias.",
      answerType: "SCALE",
      options: ["Raramente", "Em algumas semanas", "Toda semana", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "CAP-005",
      pillar: "Capacidade e gargalo",
      prompt: "A fábrica conhece a capacidade das etapas críticas?",
      helpText: "Exemplo: peças, pedidos ou horas que cada etapa entrega.",
      answerType: "SCALE",
      options: ["Mede e usa para decidir", "Conhece apenas por estimativa", "Não conhece", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = parcial; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "QUAL-001",
      pillar: "Qualidade e retrabalho",
      prompt: "Peças ou pedidos precisam voltar para correção?",
      helpText: "Considere projeto, medida, corte, usinagem, montagem e acabamento.",
      answerType: "SCALE",
      options: ["Raramente", "Toda semana", "Quase todos os dias", "Não sei/não registramos"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "QUAL-002",
      pillar: "Qualidade e retrabalho",
      prompt: "Os erros são descobertos somente no final do processo?",
      helpText: "Inclua erros encontrados na instalação ou pelo cliente.",
      answerType: "SCALE",
      options: ["Quase sempre são descobertos cedo", "Parte cedo e parte tarde", "Muitos são descobertos no final", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "QUAL-003",
      pillar: "Qualidade e retrabalho",
      prompt: "O mesmo tipo de erro volta a acontecer?",
      helpText: "Pense nos defeitos repetidos nos últimos 30 dias.",
      answerType: "SCALE",
      options: ["Raramente se repete", "Alguns erros se repetem", "Os mesmos erros voltam sempre", "Não sei/não registramos"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "QUAL-004",
      pillar: "Qualidade e retrabalho",
      prompt: "A causa do erro é registrada e tratada?",
      helpText: "Registrar a causa é diferente de apenas refazer a peça.",
      answerType: "SCALE",
      options: ["Quase sempre", "Somente nos casos maiores", "Raramente ou nunca", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = parcial; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "QUAL-005",
      pillar: "Qualidade e retrabalho",
      prompt: "A fábrica mede quantas peças passam sem correção?",
      helpText: "Pode ser uma contagem simples de aprovação na primeira passagem.",
      answerType: "SCALE",
      options: ["Mede e acompanha", "Mede às vezes", "Não mede", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = parcial; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "MAT-001",
      pillar: "Materiais e informação",
      prompt: "A produção para por falta de material ou componente?",
      helpText: "Inclua chapas, ferragens, tintas e acessórios.",
      answerType: "SCALE",
      options: ["Raramente", "Toda semana", "Quase todos os dias", "Não sei/não registramos"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "MAT-002",
      pillar: "Materiais e informação",
      prompt: "Os pedidos chegam à produção com informações incompletas?",
      helpText: "Considere projeto, medidas, ferragens e aprovações.",
      answerType: "SCALE",
      options: ["Raramente", "Alguns pedidos", "Muitos pedidos", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "MAT-003",
      pillar: "Materiais e informação",
      prompt: "A empresa precisa fazer compras urgentes?",
      helpText: "Considere compras fora do planejamento para não parar pedidos.",
      answerType: "SCALE",
      options: ["Raramente", "Algumas vezes no mês", "Toda semana ou quase todo dia", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "MAT-004",
      pillar: "Materiais e informação",
      prompt: "O saldo de estoque costuma ser diferente do estoque real?",
      helpText: "Pense nos itens que o sistema ou planilha mostra, mas não estão disponíveis.",
      answerType: "SCALE",
      options: ["Raramente", "Acontece com alguns itens", "Acontece com frequência", "Não sei/não controlamos"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "MAT-005",
      pillar: "Materiais e informação",
      prompt: "Atrasos de fornecedores mudam o plano de produção?",
      helpText: "Considere os principais materiais dos últimos 90 dias.",
      answerType: "SCALE",
      options: ["Raramente", "Em alguns pedidos", "Com frequência", "Não sei/não acompanhamos"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "GEST-001",
      pillar: "Gestão e padronização",
      prompt: "As etapas principais têm uma forma padrão de trabalho?",
      helpText: "Pode ser um padrão simples, visual ou documentado.",
      answerType: "SCALE",
      options: ["Padrão claro e usado", "Depende da pessoa ou do dia", "Cada pessoa faz de um jeito", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "GEST-002",
      pillar: "Gestão e padronização",
      prompt: "A operação para quando o dono não está presente?",
      helpText: "Pense em decisões, prioridades e resolução de problemas.",
      answerType: "SCALE",
      options: ["A equipe continua normalmente", "Algumas decisões esperam", "A operação trava ou perde muito ritmo", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "GEST-003",
      pillar: "Gestão e padronização",
      prompt: "Os problemas recebem um responsável e um prazo?",
      helpText: "Considere os problemas tratados nos últimos 30 dias.",
      answerType: "SCALE",
      options: ["Quase sempre", "Somente nos problemas maiores", "Raramente ou nunca", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = parcial; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "GEST-004",
      pillar: "Gestão e padronização",
      prompt: "As prioridades mudam durante o dia sem um critério claro?",
      helpText: "Considere urgências que interrompem a sequência combinada.",
      answerType: "SCALE",
      options: ["Raramente", "Algumas vezes por semana", "Todos os dias", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = recorrente; 5 = crítico; desconhecido não recebe nota",
    },
    {
      code: "GEST-005",
      pillar: "Gestão e padronização",
      prompt: "A gestão acompanha indicadores da operação?",
      helpText: "Exemplo: prazo, produção, retrabalho ou fila.",
      answerType: "SCALE",
      options: ["Acompanha toda semana", "Acompanha sem rotina", "Não acompanha", "Não sei"],
      required: true,
      weight: 1,
      scoringRule: "1 = controlado; 3 = parcial; 5 = crítico; desconhecido não recebe nota",
    },
  ],
  bottleneckRules: [
    {
      code: "ROTA-GARGALO-FLUXO",
      name: "Gargalo de fluxo e prazo",
      definition: "Pedidos acumulam, esperam ou atrasam porque entrada e sequência não respeitam a capacidade real.",
      supportingSignals: ["Pedidos fora do prazo", "Espera maior que processamento", "Filas recorrentes", "Muitos pedidos iniciados"],
      requiredEvidence: ["Etapa da espera", "Pedido recente", "Tempo parado estimado ou registrado"],
      contradictingEvidence: ["Fluxo estável", "Baixo trabalho em processo", "Entregas no prazo"],
      decisionRule: "Se fila e sequência forem o principal limitador, recomendar Fluxo e Fila Controlada.",
      minimumConfidence: 0.5,
      followUpQuestions: ["Em qual etapa está a maior espera?", "Qual pedido recente comprova isso?"],
    },
    {
      code: "ROTA-GARGALO-CAPACIDADE",
      name: "Gargalo de capacidade",
      definition: "Uma máquina, setor, pessoa ou competência limita o ritmo do sistema.",
      supportingSignals: ["Fila antes do recurso", "Horas extras", "Paradas e setups", "Demanda acima da capacidade"],
      requiredEvidence: ["Recurso candidato", "Fila ou perda", "Horas ou produção do recurso"],
      contradictingEvidence: ["Recurso ocioso", "Ausóncia de fila", "Bloqueio por material ou informação"],
      decisionRule: "Se a restrição for observável e recorrente, recomendar Gestão da Restrição.",
      minimumConfidence: 0.5,
      followUpQuestions: ["Qual recurso limita o ritmo?", "Qual perda recente foi observada?"],
    },
    {
      code: "ROTA-GARGALO-QUALIDADE",
      name: "Gargalo de qualidade e retrabalho",
      definition: "Erros, defeitos e correções consomem capacidade, material e prazo.",
      supportingSignals: ["Peças retornam", "Erro descoberto tarde", "Defeito recorrente", "Retrabalho sem causa"],
      requiredEvidence: ["Tipo de erro", "Frequência", "Etapa de origem ou descoberta", "Impacto observado"],
      contradictingEvidence: ["Alta aprovação de primeira", "Retrabalho raro"],
      decisionRule: "Se houver um defeito repetido que consome capacidade, recomendar Redução de Retrabalho.",
      minimumConfidence: 0.5,
      followUpQuestions: ["Qual erro mais se repete?", "Quantas ocorrências ou horas houve?"],
    },
    {
      code: "ROTA-GARGALO-MATERIAIS",
      name: "Gargalo de materiais e informação",
      definition: "A produção perde ritmo porque o pedido é liberado sem material ou informação suficiente.",
      supportingSignals: ["Parada por item", "Compra emergencial", "Projeto alterado", "Pedido aguardando aprovação"],
      requiredEvidence: ["Item ou informação faltante", "Pedido afetado", "Frequência de bloqueios"],
      contradictingEvidence: ["Pedidos liberados completos", "Material disponível no momento necessário"],
      decisionRule: "Se a falta de material ou informação bloquear o fluxo, recomendar Liberação Completa do Pedido.",
      minimumConfidence: 0.5,
      followUpQuestions: ["Qual item mais bloqueia?", "Quantos pedidos foram afetados?"],
    },
    {
      code: "ROTA-GARGALO-GESTAO",
      name: "Gargalo de gestão e padronização",
      definition: "Falta de padrão, prioridade e responsabilidade gera variação e urgência.",
      supportingSignals: ["Cada pessoa executa de um jeito", "Prioridades mudam", "Problemas sem dono", "Dependência do dono"],
      requiredEvidence: ["Processo com variação", "Exemplo recente", "Consequência observada"],
      contradictingEvidence: ["Padrão claro e utilizado", "Rotina consistente", "Ações concluídas"],
      decisionRule: "Se variação ou prioridade forem a principal causa provável, recomendar Trabalho Padronizado e Gestão à Vista.",
      minimumConfidence: 0.5,
      followUpQuestions: ["Qual processo varia mais?", "Qual exemplo recente demonstra isso?"],
    },
  ],
  abstentionRules: [
    "Abster se faltarem duas ou mais respostas no pilar candidato.",
    "Abster se não houver exemplo ou evidência mínima.",
    "Abster se a confiança ficar abaixo de 0,50.",
    "Abster se houver contradição relevante sem esclarecimento.",
    "Abster se nenhum método publicado for aplicável.",
  ],
  methods: [
    {
      code: "ROTA-FLUXO-FILA-CONTROLADA",
      name: "Fluxo e Fila Controlada",
      version: 1,
      description: "Reduzir espera e atraso controlando entrada, prioridade e trabalho em processo.",
      applicabilityRules: ["Fila e sequência são o principal limitador"],
      contraindications: ["Não aplicar isoladamente se a fila vier de quebra, falta de material ou retrabalho"],
      tradeOffs: ["Pode ser necessário iniciar menos pedidos ao mesmo tempo"],
      indicators: ["Percentual de pedidos no prazo", "Tempo de espera por etapa", "Pedidos em processo"],
      minimumEvidence: ["Percurso e espera de cinco pedidos"],
      abandonmentRules: ["Trocar o foco se a fila for explicada por outro recurso"],
      steps: [
        { order: 1, title: "Acompanhar cinco pedidos", description: "Registrar o percurso e as esperas de cinco pedidos reais.", suggestedOwner: "Gestor da fábrica", dueInDays: 5, expectedOutput: "Mapa de percurso e espera", indicator: "Tempo de espera por etapa", requiredEvidence: "Registro datado de cinco pedidos" },
        { order: 2, title: "Identificar a maior fila", description: "Comparar as etapas e marcar onde o trabalho mais espera.", suggestedOwner: "Responsável pela produção", dueInDays: 8, expectedOutput: "Etapa crítica confirmada", indicator: "Quantidade em fila", requiredEvidence: "Contagem ou foto da fila" },
        { order: 3, title: "Definir prioridade única", description: "Escolher um critério simples para ordenar os pedidos.", suggestedOwner: "Gestor da fábrica", dueInDays: 12, expectedOutput: "Regra de prioridade publicada", indicator: "Mudanças de prioridade", requiredEvidence: "Regra visóvel para a equipe" },
        { order: 4, title: "Limitar a fila", description: "Definir um limite visual antes da etapa crítica.", suggestedOwner: "Líder da etapa", dueInDays: 18, expectedOutput: "Limite de trabalho em processo", indicator: "Pedidos na fila", requiredEvidence: "Controle visual atualizado" },
        { order: 5, title: "Comparar o resultado", description: "Comparar semanalmente prazo e fila com o baseline.", suggestedOwner: "Gestor da fábrica", dueInDays: 30, expectedOutput: "Comparação antes e depois", indicator: "Pedidos no prazo", requiredEvidence: "Registro de quatro semanas" },
      ],
      successCriteria: ["Redução sustentada da espera", "Melhora das entregas no prazo"],
    },
    {
      code: "ROTA-GESTAO-RESTRICAO",
      name: "Gestão da Restrição",
      version: 1,
      description: "Confirmar, proteger e explorar o recurso que limita o resultado do sistema.",
      applicabilityRules: ["Existe restrição observável e recorrente"],
      contraindications: ["Não aplicar se o problema for sazonal ou não houver demanda suficiente"],
      tradeOffs: ["Outras etapas podem operar abaixo da capacidade local para proteger o fluxo global"],
      indicators: ["Produção por hora", "Horas produtivas", "Tempo de parada", "Fila antes da restrição"],
      minimumEvidence: ["Uma semana de produção, horas e fila do recurso candidato"],
      abandonmentRules: ["Refutar se o recurso tiver ociosidade e a fila vier de outro bloqueio"],
      steps: [
        { order: 1, title: "Medir o recurso candidato", description: "Registrar por uma semana produção, horas, paradas e fila.", suggestedOwner: "Gestor de produção", dueInDays: 7, expectedOutput: "Baseline da restrição", indicator: "Horas produtivas", requiredEvidence: "Controle diário de uma semana" },
        { order: 2, title: "Confirmar a restrição", description: "Verificar se o recurso realmente limita a saída do sistema.", suggestedOwner: "Gestor de produção", dueInDays: 10, expectedOutput: "Hipótese confirmada ou refutada", indicator: "Fila e saída do sistema", requiredEvidence: "Comparação com outras etapas" },
        { order: 3, title: "Remover interrupções", description: "Eliminar as perdas evitáveis do recurso confirmado.", suggestedOwner: "Líder da etapa", dueInDays: 15, expectedOutput: "Plano de proteção", indicator: "Tempo de parada", requiredEvidence: "Registro das interrupções removidas" },
        { order: 4, title: "Preparar antes do início", description: "Garantir material, informação e operador antes de usar o recurso.", suggestedOwner: "Líder da etapa", dueInDays: 21, expectedOutput: "Checklist de preparação", indicator: "Paradas por falta de insumo", requiredEvidence: "Checklist aplicado" },
        { order: 5, title: "Programar pela restrição", description: "Ajustar o restante da fábrica ao ritmo do recurso limitante.", suggestedOwner: "Gestor de produção", dueInDays: 30, expectedOutput: "Sequência alinhada ao gargalo", indicator: "Saída do sistema", requiredEvidence: "Programação e resultado semanal" },
      ],
      successCriteria: ["Aumento da saída do sistema", "Fila controlada antes do recurso"],
    },
    {
      code: "ROTA-REDUCAO-RETRABALHO",
      name: "Redução de Retrabalho",
      version: 1,
      description: "Reduzir o defeito recorrente de maior impacto sem criar nova falha.",
      applicabilityRules: ["Existe um tipo de erro repetido que consome capacidade"],
      contraindications: ["Não intervir em causa presumida sem delimitar e medir o defeito"],
      tradeOffs: ["A primeira semana mede o defeito antes de testar a solução"],
      indicators: ["Taxa de retrabalho", "Ocorrências", "Horas de correção", "Aprovação na primeira passagem"],
      minimumEvidence: ["Tipo, frequência e etapa de um defeito recorrente"],
      abandonmentRules: ["Trocar o método se os casos não forem comparáveis"],
      steps: [
        { order: 1, title: "Escolher um defeito", description: "Delimitar um único tipo de retrabalho recorrente.", suggestedOwner: "Gestor da fábrica", dueInDays: 3, expectedOutput: "Defeito priorizado", indicator: "Ocorrências do defeito", requiredEvidence: "Exemplos de pedidos afetados" },
        { order: 2, title: "Medir por uma semana", description: "Registrar quantidade, etapa e horas de correção.", suggestedOwner: "Responsável pela qualidade", dueInDays: 10, expectedOutput: "Baseline de retrabalho", indicator: "Horas de correção", requiredEvidence: "Registro de uma semana" },
        { order: 3, title: "Localizar origem e detecção", description: "Identificar onde o erro nasce e onde é percebido.", suggestedOwner: "Responsável pelo processo", dueInDays: 14, expectedOutput: "Mapa do defeito", indicator: "Etapa de detecção", requiredEvidence: "Amostra rastreada" },
        { order: 4, title: "Testar uma causa", description: "Aplicar uma correção piloto pequena e reversível.", suggestedOwner: "Responsável pelo processo", dueInDays: 21, expectedOutput: "Ação piloto", indicator: "Taxa de retrabalho", requiredEvidence: "Registro da mudança" },
        { order: 5, title: "Comparar antes e depois", description: "Verificar se o defeito caiu sem criar nova falha.", suggestedOwner: "Gestor da fábrica", dueInDays: 30, expectedOutput: "Decisão sobre o piloto", indicator: "Aprovação na primeira passagem", requiredEvidence: "Comparação dos dois períodos" },
      ],
      successCriteria: ["Redução do defeito escolhido", "Nenhuma nova falha relevante"],
    },
    {
      code: "ROTA-LIBERACAO-COMPLETA",
      name: "Liberação Completa do Pedido",
      version: 1,
      description: "Liberar trabalho somente quando os pré-requisitos críticos estiverem disponíveis.",
      applicabilityRules: ["Falta de material ou informação bloqueia o fluxo"],
      contraindications: ["Não aplicar isoladamente em incapacidade estrutural de fornecedor ou engenharia"],
      tradeOffs: ["Alguns pedidos aguardam antes da produção para evitar bloqueios internos"],
      indicators: ["Pedidos bloqueados", "Paradas por falta", "Compras urgentes", "Alterações após liberação"],
      minimumEvidence: ["Item faltante, pedido afetado e frequência"],
      abandonmentRules: ["Encaminhar se o bloqueio exigir projeto de fornecedor ou engenharia"],
      steps: [
        { order: 1, title: "Registrar bloqueios", description: "Listar os bloqueios recentes por material ou informação.", suggestedOwner: "Gestor ou comprador", dueInDays: 5, expectedOutput: "Lista de bloqueios", indicator: "Pedidos bloqueados", requiredEvidence: "Pedidos recentes afetados" },
        { order: 2, title: "Priorizar pré-requisitos", description: "Identificar os itens que mais faltam antes da liberação.", suggestedOwner: "Responsável por projetos", dueInDays: 9, expectedOutput: "Lista de pré-requisitos críticos", indicator: "Frequência de falta", requiredEvidence: "Contagem por item" },
        { order: 3, title: "Criar checklist curto", description: "Definir as confirmações mínimas para liberar um pedido.", suggestedOwner: "Responsável por projetos", dueInDays: 14, expectedOutput: "Checklist de liberação", indicator: "Pedidos liberados completos", requiredEvidence: "Checklist publicado" },
        { order: 4, title: "Definir responsável", description: "Nomear quem confere os pré-requisitos antes da produção.", suggestedOwner: "Gestor da fábrica", dueInDays: 16, expectedOutput: "Responsabilidade definida", indicator: "Checklists conferidos", requiredEvidence: "Responsável comunicado" },
        { order: 5, title: "Testar por duas semanas", description: "Aplicar o checklist e comparar os bloqueios.", suggestedOwner: "Responsável pela liberação", dueInDays: 30, expectedOutput: "Resultado do teste", indicator: "Pedidos parados após liberação", requiredEvidence: "Duas semanas de checklists" },
      ],
      successCriteria: ["Menos pedidos parados depois de liberados"],
    },
    {
      code: "ROTA-TRABALHO-PADRONIZADO",
      name: "Trabalho Padronizado e Gestão à Vista",
      version: 1,
      description: "Estabilizar uma operação crítica e criar responsabilidade visóvel.",
      applicabilityRules: ["Variação de execução ou prioridade é a principal causa provável"],
      contraindications: ["Não criar burocracia ou documentos longos para processos simples"],
      tradeOffs: ["Exige disciplina de atualização e pode encontrar resistência inicial"],
      indicators: ["Aderência ao padrão", "Variação do resultado", "Ações no prazo", "Urgências"],
      minimumEvidence: ["Processo com variação, exemplo recente e consequência"],
      abandonmentRules: ["Trocar o foco se a variação for causada por equipamento, material ou produto"],
      steps: [
        { order: 1, title: "Escolher o processo crítico", description: "Selecionar uma operação com variação e impacto observados.", suggestedOwner: "Gestor da fábrica", dueInDays: 3, expectedOutput: "Processo delimitado", indicator: "Variação do resultado", requiredEvidence: "Exemplo recente" },
        { order: 2, title: "Observar a execução real", description: "Acompanhar como diferentes pessoas executam o processo.", suggestedOwner: "Responsável pelo processo", dueInDays: 7, expectedOutput: "Registro das variações", indicator: "Formas diferentes de executar", requiredEvidence: "Observação datada" },
        { order: 3, title: "Definir padrão simples", description: "Criar sequência e critério de saída visual.", suggestedOwner: "Responsável pelo processo", dueInDays: 14, expectedOutput: "Padrão visual", indicator: "Aderência ao padrão", requiredEvidence: "Padrão publicado" },
        { order: 4, title: "Testar com a equipe", description: "Aplicar o padrão e registrar dúvidas ou falhas.", suggestedOwner: "Líder da equipe", dueInDays: 21, expectedOutput: "Padrão testado", indicator: "Aderência", requiredEvidence: "Confirmação da equipe" },
        { order: 5, title: "Revisar duas vezes por semana", description: "Acompanhar problemas, responsáveis e prazos em gestão à vista.", suggestedOwner: "Gestor da fábrica", dueInDays: 30, expectedOutput: "Rotina de gestão", indicator: "Ações concluídas no prazo", requiredEvidence: "Registro das revisões" },
      ],
      successCriteria: ["Menor variação", "Maior conclusão de ações"],
    },
  ],
};


