// Scoped one-time replacement requested by the owner. Does not delete diagnoses or conversations.
import { loadEnvFile } from "node:process";
import { readFileSync,mkdirSync,existsSync,statSync,writeFileSync } from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import { DEV_COMPANY_ID } from "../src/core/development";
import { executableCooPlanSchema,readWorkshop,type WorkshopState } from "../src/core/coo-workshop";
import { persistWorkshopPlan } from "../src/server/ai/workshop-persistence";
loadEnvFile(".env");
const url=new URL(process.env.DATABASE_URL!);
assert.ok(url.hostname==="127.0.0.1"&&url.port==="5433","Somente banco local");
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL!})});
async function main(){
 assert.ok(process.argv.includes("--replace-tested-candidate"),"Requer confirmação do exemplo testado");
 const candidate=JSON.parse(readFileSync("backups/executable-plan-candidate.json","utf8"));
 assert.equal(candidate.oldPlanId,"coo-plan-coo-workshop-cmtgmz3me0000hsupb2k68pxt");
 const plan=executableCooPlanSchema.parse(candidate.plan);assert.equal(plan.initiatives.length,3);assert.equal(plan.initiatives.filter(i=>i.kind==="PRIMARY").length,1);
 const old=await db.actionPlan.findFirstOrThrow({where:{id:candidate.oldPlanId,companyId:DEV_COMPANY_ID}});
 assert.equal(old.updatedAt.toISOString(),candidate.oldUpdatedAt,"O plano mudou desde a geração");
 const counts={diagnoses:await db.diagnosticSession.count({where:{companyId:DEV_COMPANY_ID}}),messages:await db.conversationMessage.count({where:{thread:{companyId:DEV_COMPANY_ID}}})};
 const backup=path.resolve("backups",`plan-before-replacement-${new Date().toISOString().replace(/[:.]/g,"-")}.dump`);
 assert.ok(backup.startsWith(path.resolve("backups")+path.sep));assert.ok(!existsSync(backup));mkdirSync(path.dirname(backup),{recursive:true});
 const dumped=spawnSync("C:/Program Files/PostgreSQL/17/bin/pg_dump.exe",["-Fc","-f",backup],{env:{...process.env,PGHOST:url.hostname,PGPORT:url.port,PGDATABASE:decodeURIComponent(url.pathname.slice(1)),PGUSER:decodeURIComponent(url.username),PGPASSWORD:decodeURIComponent(url.password)},encoding:"utf8",windowsHide:true});
 assert.equal(dumped.status,0,"Backup falhou; plano preservado");assert.ok(statSync(backup).size>0);
 const newId=`coo-plan-demo-${randomUUID()}`;
 await db.$transaction(async tx=>{
  await tx.$queryRaw`SELECT id FROM "Company" WHERE id = ${DEV_COMPANY_ID} FOR UPDATE`;
  await tx.$queryRaw`SELECT id FROM "ConversationThread" WHERE id = ${candidate.threadId} AND "companyId" = ${DEV_COMPANY_ID} FOR UPDATE`;
  const thread=await tx.conversationThread.findFirstOrThrow({where:{id:candidate.threadId,companyId:DEV_COMPANY_ID}});assert.equal(thread.generationId,null,"Conversa em andamento");
  const prior=readWorkshop(thread.workflowState);assert.ok(prior);assert.equal(prior.planId,old.id);assert.equal(prior.diagnosticId,candidate.diagnosticId);
  assert.equal(prior.decision?.primaryTitle,plan.initiatives.find(i=>i.kind==="PRIMARY")?.title);
  const current=await tx.actionPlan.findUniqueOrThrow({where:{id:old.id}});assert.equal(current.updatedAt.toISOString(),candidate.oldUpdatedAt);
  const state:WorkshopState={...prior,stage:"REVIEW",revision:prior.revision+1,furthestStage:5,planId:newId,plan,summary:"Exemplo completo solicitado pelo proprietário: mantém a prioridade da lixa já confirmada e acrescenta duas sugestões de apoio. 5W2H e passos revisados para os formulários reais da plataforma. Relatos continuam declarados, não medidos. Revisar responsáveis, prazos e ações secundárias antes de aprovar. Nenhuma tarefa iniciada ou resultado comprovado.",history:[...prior.history,{revision:prior.revision,stage:prior.stage,summary:"Plano anterior substituído a pedido do proprietário; backup realizado. Conversas e diagnóstico preservados.",at:new Date().toISOString()}]};
  const saved=await persistWorkshopPlan(tx,DEV_COMPANY_ID,thread.id,state);
  const created=await tx.actionPlan.findUniqueOrThrow({where:{id:newId}});
  await tx.actionPlan.update({where:{id:newId},data:{title:"Exemplo — Lixa, filas e retrabalho · Plano 5W2H",baseline:{...Object(created.baseline),demo:true,previousPlanId:old.id}}});
  await tx.conversationThread.update({where:{id:thread.id},data:{workflowState:saved as never,lastMessageAt:new Date()}});
  await tx.conversationMessage.create({data:{threadId:thread.id,role:"ASSISTANT",content:"Exemplo atualizado a pedido do proprietário. Mantive a investigação da lixa e preparei duas iniciativas de apoio: fila entre etapas e registro de retrabalho. O plano tem 5W2H, passos e formulários prontos. Os relatos anteriores não viraram medições; as novas ações são sugestões pendentes de aprovação. Abra Revisar plano para conferir e testar os registros sem salvar dados reais.",metadata:{source:"PLAN_REPLACEMENT_NOTICE",demo:true,planId:newId}}});
  const tasks=await tx.task.findMany({where:{actionPlanId:old.id,companyId:DEV_COMPANY_ID},select:{id:true}}),checkins=await tx.progressCheckin.findMany({where:{actionPlanId:old.id,companyId:DEV_COMPANY_ID},select:{id:true}});
  const taskIds=tasks.map(t=>t.id),checkinIds=checkins.map(c=>c.id);
  await tx.evidenceOutput.deleteMany({where:{companyId:DEV_COMPANY_ID,OR:[{taskId:{in:taskIds}},{checkinId:{in:checkinIds}}]}});
  await tx.metricMeasurement.deleteMany({where:{companyId:DEV_COMPANY_ID,checkinId:{in:checkinIds}}});
  await tx.progressCheckin.deleteMany({where:{companyId:DEV_COMPANY_ID,id:{in:checkinIds}}});
  await tx.lessonAssignment.deleteMany({where:{companyId:DEV_COMPANY_ID,actionPlanId:old.id}});
  await tx.companyMemory.deleteMany({where:{companyId:DEV_COMPANY_ID,OR:[{sourceType:"TASK",sourceId:{in:taskIds}},{sourceType:"CHECKIN",sourceId:{in:checkinIds}}]}});
  await tx.actionPlan.delete({where:{id:old.id}});
 },{timeout:30000});
 assert.equal(await db.diagnosticSession.count({where:{companyId:DEV_COMPANY_ID}}),counts.diagnoses);
 assert.equal(await db.conversationMessage.count({where:{thread:{companyId:DEV_COMPANY_ID}}}),counts.messages+1);
 const tasks=await db.task.findMany({where:{actionPlanId:newId},orderBy:{sortOrder:"asc"},select:{id:true,title:true,status:true}});
 assert.equal(tasks.length,3);assert.ok(tasks.every(t=>t.status==="BACKLOG"));
 const result={planId:newId,url:`http://127.0.0.1:3000/plano-de-acao?id=${newId}`,status:"DRAFT",tasks,backup};
 writeFileSync("backups/executable-plan-result.json",JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}
main().catch(e=>{console.error(e instanceof Error?e.message:"Falha na substituição");process.exitCode=1;}).finally(()=>db.$disconnect());
