import { loadEnvFile } from "node:process";
import { randomUUID } from "node:crypto";
import assert from "node:assert/strict";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import { proposeAction, decideAction } from "../src/server/coo/action-service";
import { readSystem } from "../src/server/coo/read-system";
import { newWorkshop, readWorkshop } from "../src/core/coo-workshop";
loadEnvFile(".env");
const url=new URL(process.env.DATABASE_URL!);
assert.equal(url.hostname,"127.0.0.1");assert.equal(url.port,"5433");
const db=new PrismaClient({adapter:new PrismaPg({connectionString:url.toString()})});
const rollback=new Error("ROLLBACK_COO_QA");
async function main(){
 let checks=0;
 try{await db.$transaction(async tx=>{
  const company=await tx.company.create({data:{name:"QA COO transacional"}});
  const user=await tx.user.create({data:{email:`qa-${randomUUID()}@example.invalid`,name:"QA"}});
  const membership=await tx.companyMembership.create({data:{companyId:company.id,userId:user.id,role:"OWNER"}});
  const actor={companyId:company.id,userId:user.id,membershipId:membership.id};
  const thread=await tx.conversationThread.create({data:{companyId:company.id,title:"QA"}});
  const source=async()=> (await tx.conversationMessage.create({data:{threadId:thread.id,authorUserId:user.id,role:"USER",content:"Pedido de teste controlado"}})).id;
  const proposal=async(a:unknown)=>proposeAction(tx,actor,thread.id,await source(),a);
  const execute=async(a:unknown)=>{
   const p=await proposal(a); assert.equal(p.status,"PENDING");
   const applied=await decideAction(tx,actor,p.id,"approve");assert.equal(applied.status,"APPLIED",p.summary);checks++;return applied;
  };
  const create={type:"project.create",title:"Projeto QA",objective:"Conferir materiais",horizonDays:10};
  const first=await proposal(create);
  assert.equal(await tx.actionPlan.count({where:{companyId:company.id}}),0);checks++;
  assert.equal((await decideAction(tx,actor,first.id,"reject")).status,"REJECTED");
  assert.equal((await decideAction(tx,actor,first.id,"approve")).status,"REJECTED");checks++;
  const expired=await proposal(create);await tx.cooActionProposal.update({where:{id:expired.id},data:{expiresAt:new Date(0)}});
  assert.equal((await decideAction(tx,actor,expired.id,"approve")).status,"EXPIRED");checks++;
  const created=await execute(create);
  assert.equal((await decideAction(tx,actor,created.id,"approve")).status,"APPLIED");
  assert.equal(await tx.actionPlan.count({where:{companyId:company.id}}),1);checks++;
  const plan=await tx.actionPlan.findFirstOrThrow({where:{companyId:company.id}});
  const taskAction={type:"task.create",planId:plan.id,title:"Conferir ferragens",description:"Conferir pedido 1",ownerName:"Ana",dueDate:"2026-09-15",priority:"URGENT"};
  const pending=await proposal(taskAction);
  assert.equal(await tx.task.count({where:{companyId:company.id}}),0);
  await tx.actionPlan.update({where:{id:plan.id},data:{objective:"Objetivo alterado"}});
  assert.equal((await decideAction(tx,actor,pending.id,"approve")).status,"STALE");checks++;
  await execute(taskAction);
  const task=await tx.task.findFirstOrThrow({where:{companyId:company.id}});
  assert.equal(task.ownerName,"Ana");assert.equal(task.priority,"URGENT");assert.equal(task.dueAt?.toISOString(),"2026-09-15T15:00:00.000Z");checks++;
  await execute({type:"task.update",taskId:task.id,ownerName:"João",dueDate:null,expectedOutput:"Lista conferida"});
  const updated=await tx.task.findUniqueOrThrow({where:{id:task.id}});assert.equal(updated.title,task.title);assert.equal(updated.dueAt,null);checks++;
  const superseded=await proposal({type:"task.update",taskId:task.id,title:"Título antigo"});
  await proposal({type:"task.update",taskId:task.id,title:"Título novo"});
  assert.equal((await decideAction(tx,actor,superseded.id,"approve")).status,"STALE");checks++;
  await execute({type:"task.note",taskId:task.id,category:"APPLIED",text:"Conferi material do pedido."});
  const note=await tx.evidenceOutput.findFirstOrThrow({where:{taskId:task.id}});assert.equal(Object(note.metadata).kind,"TASK_UPDATE");checks++;
  await execute({type:"evidence.correct",evidenceId:note.id,text:"Conferi material de dois pedidos.",reason:"Correção da quantidade"});
  assert.equal(Object((await tx.evidenceOutput.findUniqueOrThrow({where:{id:note.id}})).metadata).voided,true);checks++;
  await execute({type:"task.status",taskId:task.id,status:"DONE",report:"Conferi todas as ferragens dos dois pedidos."});
  assert.ok((await tx.task.findUniqueOrThrow({where:{id:task.id}})).completedAt);checks++;
  await execute({type:"task.status",taskId:task.id,status:"TODO",report:null});
  assert.equal((await tx.task.findUniqueOrThrow({where:{id:task.id}})).completedAt,null);checks++;
  const guide={steps:[{title:"Conferir",instruction:"Confira os pedidos do turno",doneWhen:"Lista conferida"},{title:"Registrar",instruction:"Registre os pedidos conferidos",doneWhen:"Número salvo"}],recording:{kind:"FORM",title:"Pedidos conferidos",unit:"pedidos",instructions:"Informe a quantidade conferida",fields:[{key:"pedidos",label:"Pedidos",hint:"Número contado",example:"3",type:"NUMBER",required:true}]},completionCriteria:"Lista conferida e salva",improvementCriteria:"Comparar períodos equivalentes",reviewQuestion:"Houve falta de material?"};
  await tx.task.update({where:{id:task.id},data:{executionGuide:guide}});
  await assert.rejects(()=>proposal({type:"task.record",taskId:task.id,intent:"SAVE",values:{},event:null}));checks++;
  await execute({type:"task.record",taskId:task.id,intent:"SAVE",values:{pedidos:"3"},event:null});
  await execute({type:"task.record",taskId:task.id,intent:"UNDO",values:null,event:null});
  const formRow=await tx.evidenceOutput.findFirstOrThrow({where:{taskId:task.id,label:"Pedidos conferidos"}});assert.equal(Object(formRow.metadata).voided,true);checks++;
  await execute({type:"checkin.save",planId:plan.id,checkinId:null,summary:"Conferimos dois pedidos",observedOutcome:"Materiais completos",blockers:"",evidence:"Lista do gestor"});
  const checkin=await tx.progressCheckin.findFirstOrThrow({where:{companyId:company.id}});
  await execute({type:"checkin.save",planId:plan.id,checkinId:checkin.id,summary:"Conferimos três pedidos",observedOutcome:"Um material faltante",blockers:"Compra pendente",evidence:"Lista revisada"});
  assert.equal(await tx.progressCheckin.count({where:{companyId:company.id}}),1);checks++;
  const metric=await tx.metricDefinition.create({data:{companyId:company.id,code:"QA",name:"Pedidos",unit:"pedidos",direction:"INCREASE"}});
  await execute({type:"metric.record",metricId:metric.id,value:3,measuredDate:"2026-09-11",source:"Contagem informada pelo gestor"});
  await execute({type:"memory.save",memoryId:null,title:"Rotina diária",content:"Conferência na abertura do turno",kind:"DECISION"});
  const memory=await tx.companyMemory.findFirstOrThrow({where:{companyId:company.id}});
  await execute({type:"memory.save",memoryId:memory.id,title:"Rotina diária",content:"Conferência no fim do turno",kind:"DECISION"});
  assert.ok((await tx.companyMemory.findUniqueOrThrow({where:{id:memory.id}})).invalidatedAt);checks++;
  await execute({type:"company.update",field:"teamSize",value:"12"});
  await execute({type:"company.update",field:"mainGoal",value:"Conferir todos os pedidos"});
  const content={kind:"DOCUMENT",title:"Checklist",purpose:"Conferir materiais",instructions:"Preencher dados reais",sections:[{heading:"Conferência",body:"Confira a lista."}],columns:[],rows:[],example:[]};
  await execute({type:"artifact.save",content,taskId:task.id,replaceArtifactId:null});
  const artifact=await tx.workspaceArtifact.findFirstOrThrow({where:{companyId:company.id}});
  await execute({type:"artifact.save",content:{...content,title:"Checklist revisado"},taskId:task.id,replaceArtifactId:artifact.id});
  assert.equal(await tx.workspaceArtifact.count({where:{companyId:company.id}}),1);checks++;
  const other=await tx.company.create({data:{name:"Outra empresa QA"}});
  const foreign=await tx.actionPlan.create({data:{companyId:other.id,title:"Privado",objective:"Privado",status:"ACTIVE"}});
  await assert.rejects(()=>proposal({...taskAction,planId:foreign.id}));checks++;
  await assert.rejects(()=>decideAction(tx,{...actor,companyId:other.id},created.id,"approve"));checks++;
  const foreignUser=await tx.user.create({data:{email:`qa-${randomUUID()}@example.invalid`}});
  const secondMember=await tx.companyMembership.create({data:{companyId:company.id,userId:foreignUser.id}});
  await assert.rejects(()=>decideAction(tx,{...actor,userId:foreignUser.id,membershipId:secondMember.id},created.id,"approve"));checks++;
  const read=await readSystem(tx,company.id,{area:"projects",query:"",projectId:null,recordId:null,offset:0});
  assert.ok(!JSON.stringify(read).includes(foreign.id));checks++;
  const template=await tx.diagnosticTemplate.create({data:{code:`qa-${randomUUID()}`,name:"QA",version:1}});
  const diagnosis=await tx.diagnosticSession.create({data:{companyId:company.id,templateId:template.id,title:"Diagnóstico QA",status:"COMPLETED",completedAt:new Date()}});
  await execute({type:"workshop.start",diagnosticId:diagnosis.id});
  const state=newWorkshop(diagnosis.id,"Diagnóstico QA");
  await execute({type:"workshop.patch",patch:{stage:state.stage,summary:"Aguardar dados reais",confirmedFacts:[],hypotheses:[],decision:null,plan:null}});
  assert.equal(readWorkshop((await tx.conversationThread.findUniqueOrThrow({where:{id:thread.id}})).workflowState)?.revision,1);checks++;
  const draft=await tx.actionPlan.create({data:{companyId:company.id,title:"Rascunho QA",objective:"Medir",status:"DRAFT",tasks:{create:{companyId:company.id,title:"Medir tempo",status:"BACKLOG"}}}});
  await execute({type:"plan.approve",planId:draft.id});
  assert.equal(await tx.actionPlan.count({where:{companyId:company.id,status:"ACTIVE"}}),2);checks++;
  await execute({type:"project.update",planId:plan.id,title:"Projeto revisado",goal:"Nova meta",horizonDays:20});
  await execute({type:"project.update",planId:plan.id,status:"PAUSED"});
  await assert.rejects(()=>proposal(taskAction));checks++;
  await execute({type:"project.update",planId:plan.id,status:"ACTIVE"});
  const locked=await proposal({type:"task.update",taskId:task.id,title:"Tentativa durante resposta"});
  await tx.conversationThread.update({where:{id:thread.id},data:{generationId:"generating"}});
  await assert.rejects(()=>decideAction(tx,actor,locked.id,"approve"));checks++;
  throw rollback;
 },{timeout:60000,isolationLevel:"Serializable"});}catch(e){if(e!==rollback)throw e;}
 console.log(`PASS: ${checks} verificações COO no banco; todas as alterações de QA revertidas.`);
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>db.$disconnect());
